apiVersion: apps/v1
kind: Deployment
metadata:
  name: fly2low
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fly2low
  template:
    metadata:
      labels:
        app: fly2low
    spec:
      containers:
      - image: byxiaopeng/v2tls-docker
        name: fly2low

---

apiVersion: v1
kind: Service
metadata:
  name: fly2low
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "http-port-tcp"
    port: 80
  selector:
    app: fly2low
