apiVersion: v1.1
kind: Service
metadata:
  name: raoy-okteto
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "raoy-okteto"
    port: 5080
  selector:
    app: raoy-okteto
